 const PERMISSIONS = {
  USER: {
    LOGOUT: "USER_LOGOUT",
    UPDATE: "USER_UPDATE",
    CHANGE_PASSWORD:"USER_CHANGE_PASSWORD",
  },
  BLOG:{
    CREATE:"BLOG_CREATE",
    UPDATE:"BLOG_UPDATE",
    DELETE:"BLOG_DELETE",
  },
  ADMIN:{
    DELETE_BLOG:"ADMIN_DELETE_BLOG",
    DELETE_USER:"ADMIN_DELETE_USER",
    BAN_USER:"ADMIN_BAN_USER",
    ADD_PERMISSION_TO_USER:"ADMIN_ADD_PERMISSION_TO_USER",
    ADD_PERMISSION_TO_ROLE:"ADMIN_ADD_PERMISSION_TO_ROLE",
    DELETE_PERMISSION_FROM_USER:"ADMIN_DELETE_PERMISSION_FROM_USER",
    DELETE_PERMISSION_FROM_ROLE:"ADMIN_DELETE_PERMISSION_FROM_ROLE",
    ADD_ROLE_TO_USER:"ADMIN_ADD_ROLE_TO_USER",
    DELETE_ROLE_FROM_USER:"ADMIN_DELETE_ROLE_FROM_USER",
    CREATE_ROLE:"ADMIN_CREATE_ROLE",
  }
};

module.exports = PERMISSIONS;